### ISSUE TITLE
Hooks System

### ISSUE THREAD

**Issue by TimTims** [WildPHP/Wild-IRC-Bot#14]
Implement `Hooks` System.

**Comment by Yoshi2889** [comment]
<NanoSector> Setup a constructor that returns the hooks that need to be registered, then the bot registers the hooks
<NanoSector> The class can't register by itself because it's half initialised
<NanoSector> and you need to pass an instance of the class for the bot to be able to call it
<NanoSector> hmm
<NanoSector> Say a class contains function AHook, it'd return an array('the_hook_name', 'AHook');
<NanoSector> then the bot would know that it needs to hook the function AHook of class A into hook the_hook_name, and it can register it
<NanoSector> $bot->hooks->register('the_hook_name', array($class_A, 'AHook'));
<TimTims> Ok
<NanoSector> Then the hooks manager should check the given input and check if the function exists, actually register the function and keep track of it
<NanoSector> If we want to get into dynamic removing/adding of commands we have some challenges to accept as well
<NanoSector> Removing a command should not need cleaning up of hooks persay since the hook system will check if a function exists before calling it
<NanoSector> But adding a command needs to process the adding of hooks all over

**Comment by Amunak** [comment]
I guess we'll implement a proper event manager for modules to use.

A module should be able to:
* register a new event with the bot when it is loaded
* register a listener that will be called every time its corresponding event is fired
* register a listener non-conditionally (it doesn't fail when the event doesn't exist) - I'd implement this just with an exception - if the module registering the listener decides to catch it and do nothing they can
* fire an existing event
* give the listener a priority setting so that you can manipulate the order in which listeners are called (i.e. some kind of logging would want to listen as last in case the event is cancelled or modified)
* pass data through the event, cancelling the event, editing the data, etc.

**Comment by Yoshi2889** [comment]
The same concept as hooks I think. Variables would be passed by reference so the listeners can use them.

**Comment by Yoshi2889** [comment]
I think this is pretty much covered with the event manager in the 'new' bot, unless you have ideas that take it further?

**Comment by Amunak** [comment]
The basic thing is implemented, closing the issue. We can make improvements down the line.
