### ISSUE TITLE
Auth: Look for OPs or Voice 

### ISSUE THREAD

**Issue by Yoshi2889** [WildPHP/Wild-IRC-Bot#39]
The Auth module should be able to look for OPs and voiced users in a channel and give them privileges. Great suggestion by Stifler.

**Comment by Amunak** [comment]
Yeah, I feel like ops, halfops, owners, people with voice, but also regular users should be a special "user" in the bot which would allow a very fine-grained control over what permissions those people get.

Most bots just ignore in-channel statuses and I feel like that's a huge issue because in no way should one not distinguish between an anonymous user that is marked as a channel owner by the nework and anonymous user that's just an ordinary client.

**Comment by Yoshi2889** [comment]
We probably want the Auth module to depend on ChannelManager in that case, and have ChannelManager have information about each channel ready.

That also means we should track MODE changes and people joining and leaving, on a per-channel basis.

**Comment by Amunak** [comment]
yeah, when the auth module is loaded (or this could possibly be a separate module that would just provide this optional functionality to the auth module) we definitely do want to track people who are on channels with the bot and their status (I believe the channel manager was supposed to do this anyway).

**Comment by Yoshi2889** [comment]
Yeah I believe ChannelManager was supposed to create and manage entries for each channel. We've never gotten around to implementing that properly, beyond the bot itself.

**Comment by Yoshi2889** [comment]
I'll move this to Auth's repo once it comes available.

**Comment by Yoshi2889** [comment]
Please see #74.
